
package at.ac.tuwien.infosys.aic11.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2011-11-01T17:02:48.397+01:00
 * Generated source version: 2.3.7
 * 
 */
public final class IRegistryService_RegistryService_Client {

    private static final QName SERVICE_NAME = new QName("http://services.aic11.infosys.tuwien.ac.at/", "Registry_Service");

    private IRegistryService_RegistryService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RegistryService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RegistryService ss = new RegistryService(wsdlURL, SERVICE_NAME);
        IRegistryService port = ss.getRegistryService();  
        
        {
        System.out.println("Invoking query...");
        at.ac.tuwien.infosys.aic11.services.DisbursementPreference _query_arg0 = new BankTransfer();
        ((BankTransfer)_query_arg0).bankName = "foobar";
        ((BankTransfer)_query_arg0).bic = "1234";
        ((BankTransfer)_query_arg0).iban = "12342234";
        try {
            at.ac.tuwien.infosys.aic11.services.WsdlEndpoint _query__return = port.query(_query_arg0);
            System.out.println("query.result=" + _query__return);

        } catch (InvalidParameterException e) { 
            System.out.println("Expected exception: InvalidParameterException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
