package at.ac.tuwien.infosys.aic11.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2011-11-01T17:13:08.372+01:00
 * Generated source version: 2.3.7
 * 
 */
@WebService(targetNamespace = "http://services.aic11.infosys.tuwien.ac.at/", name = "IRegistryService")
@XmlSeeAlso({ObjectFactory.class})
public interface IRegistryService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://services.aic11.infosys.tuwien.ac.at/", className = "at.ac.tuwien.infosys.aic11.services.Query")
    @WebMethod
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://services.aic11.infosys.tuwien.ac.at/", className = "at.ac.tuwien.infosys.aic11.services.QueryResponse")
    public at.ac.tuwien.infosys.aic11.services.WsdlEndpoint query(
        @WebParam(name = "arg0", targetNamespace = "")
        at.ac.tuwien.infosys.aic11.services.DisbursementPreference arg0
    ) throws InvalidParameterException;
}
